language: c

compiler:
  - clang
  - gcc

install:
  - sudo pip install pytest
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y valgrind
  - wget http://googletest.googlecode.com/files/gtest-1.7.0.zip
  - unzip gtest-1.7.0.zip
  - cd gtest-1.7.0
  - ./configure
  - make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a lib/.libs/* /usr/lib/
  - cd ..

script:
  - make test_functional
  - make test_unit
  - make test_valgrind
